### ISSUE TITLE
Feat : Add levels to the game

### ISSUE THREAD

**Issue by Xciyang** [shzr-2003/classroom#1]
通过设置关卡增加可玩性（游戏时长）。

每关可以限制玩家的每步距离，鳖的随机移动及范围等实现难度的递增。

Increase playability by setting levels (playing time).

Each level can be limited by the player's step distance, *bie*'s random movement and range to achieve increased difficulty.

**Comment by shzr-2003** [comment]
emmmm
但是这个游戏其实是个角色扮演游戏啊（雾
不过增加难度我可以考虑一下，比如增加loli的出现概率（雾，这样就能引导玩家准确计算要走多少步

**Comment by shzr-2003** [comment]
其实这个游戏应该是这样一个“作为高中新生加入信息组，提高OI水平，AKIOI，以为走上人生巅峰，最后却被教育部取消保送资格”的悲剧故事。（雾     在过程中，还可以刷各个角色的好感度，结交朋友之类的。

**Comment by Xciyang** [comment]
> 其实这个游戏应该是这样一个“作为高中新生加入信息组，提高OI水平，AKIOI，以为走上人生巅峰，最后却被教育部取消保送资格”的悲剧故事。（雾 在过程中，还可以刷各个角色的好感度，结交朋友之类的。

不是打鳖游戏啊（

期待下一个更新。

**Comment by shzr-2003** [comment]
其实提高鳖好感度的方式就是多玩几次打鳖游戏（逃
