### ISSUE TITLE
我似乎发现了 Bug！

### ISSUE THREAD

**Issue by Challestend** [shzr-2003/classroom#2]
![](https://i.loli.net/2020/02/09/8e3C6xbvUDzTA1p.png)

如图，当一只鳖生成在桌子上时，如果我试图移动到它的位置，程序并没有理我。而如果我再次输入一些字符，程序会提醒我「再走就出去了」。

以及，程序提醒「您还没有打完现在的这只鳖呢」时会多出来一句「再走就出去了」。

以上……应该可以算是 Bug 吧（

**Comment by shzr-2003** [comment]
这确实是一个bug......因为我在更新带桌子和人物的地图时，忘记了调试鳖的部分，已更新

**Comment by shzr-2003** [comment]
另一件事情是，您要不要填一下自己的语录呀~
需要：
5句打招呼的话（就是开始对话时说的第一句话）
10句普通的闲聊（当然多多益善）
这些句子最好能体现好感度的逐渐增加，不过您也可以前9句都沉默，最后再说话（逃
